Fix `upload-db-dump` action script
It just failed:

    Run git checkout db-dumps
    error: Your local changes to the following files would be overwritten by checkout:
	    util/dev-config/config.toml
    Please commit your changes or stash them before you switch branches.

Well, I still haven't tested this, so we will see during the next
release :P